# syntax=docker/dockerfile:1.2

FROM bitnami/wordpress@sha256:c1bb65c0bb60d22ba572a039614a855164911b39ff6a0d8e38e1e8fd6c8619f7

ARG WP_USERNAME
ARG WP_PASSWORD
ARG WP_EMAIL
ARG WP_FIRSTNAME
ARG WP_LASTNAME
ARG WP_BLOGNAME
ARG WP_MULTISITE_HOST
ARG DB_HOST
ARG DB_PORT
ARG DB_USER
ARG DB_PASSWORD
ARG DB_NAME
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_USER
ARG SMTP_PASSWORD

# WORDPRESS
ENV WORDPRESS_USERNAME=$WP_USERNAME
ENV WORDPRESS_PASSWORD=$WP_PASSWORD
ENV WORDPRESS_EMAIL=$WP_EMAIL
ENV WORDPRESS_FIRST_NAME=$WP_FIRSTNAME
ENV WORDPRESS_LAST_NAME=$WP_LASTNAME
ENV WORDPRESS_BLOG_NAME=$wp_blogname
ENV WORDPRESS_HTACCESS_OVERRIDE_NONE=no
ENV WORDPRESS_ENABLE_HTACCESS_PERSISTENCE=yes

# MULTISITE
ENV WORDPRESS_ENABLE_MULTISITE=yes
ENV WORDPRESS_MULTISITE_HOST=$WP_MULTISITE_HOST

# MYSQL
ENV WORDPRESS_DATABASE_HOST=$DB_HOST
ENV WORDPRESS_DATABASE_PORT_NUMBER=$DB_PORT
ENV WORDPRESS_DATABASE_USER=$DB_USER
ENV WORDPRESS_DATABASE_PASSWORD=$DB_PASSWORD
ENV WORDPRESS_DATABASE_NAME=$DB_NAME

# SMTP
ENV WORDPRESS_SMTP_HOST=$SMTP_HOST
ENV WORDPRESS_SMTP_PORT=$SMTP_PORT
ENV WORDPRESS_SMTP_USER=$SMTP_USER
ENV WORDPRESS_SMTP_PASSWORD=$SMTP_PASSWORD