FROM bitnami/wordpress:latest

ARG DB_HOST
ARG DB_USER
ARG DB_PASSWORD
ARG DB_NAME
ARG DB_PORT
ARG MULTISITE_HOST

ENV WORDPRESS_DATABASE_HOST=$DB_HOST
ENV WORDPRESS_DATABASE_PORT_NUMBER=$DB_PORT
ENV WORDPRESS_DATABASE_USER=$DB_USER
ENV WORDPRESS_DATABASE_PASSWORD=$DB_PASSWORD
ENV WORDPRESS_DATABASE_NAME=$DB_NAME
ENV WORDPRESS_HTACCESS_OVERRIDE_NONE=no
ENV WORDPRESS_ENABLE_HTACCESS_PERSISTENCE=yes

# MULTISITE
ENV WORDPRESS_ENABLE_MULTISITE=yes
ENV WORDPRESS_MULTISITE_HOST=$MULTISITE_HOST